### ISSUE TITLE
Header members incorrespondence

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#109] opened 2018-09-14 03:11 UTC
In roslibjs, we found the `builtin_interfaces/Time` members are `secs` and `nsecs`. While in ROS2, the members are `sec` and `nanosec`. When we work the bridge with roslibjs, there will be errors in the log of bridge. Which side should be updated to keep correspondence?

**Comment by qiuzhong** [comment] 2018-09-14 03:11
@minggangw

**Comment by minggangw** [comment] 2018-09-14 03:28
We must follow the definition of ROS 2 for the [Time](https://github.com/ros2/rcl_interfaces/blob/master/builtin_interfaces/msg/Time.msg) in order to use the right JavaScript message.

**Comment by qiuzhong** [comment] 2018-09-14 06:54
Should I file an issue for this in roslibjs repo? I'm not sure if roslibjs is responsible to work with ROS2.

**Comment by minggangw** [comment] 2018-09-14 07:03
I don't think this is a bug for roslibjs, as it originates in the change of .msg definition.

**Comment by minggangw** [comment] 2018-09-19 08:31
As this issue is caused by the different definition of ROS 2 from ROS 1,  I am going to close it, thanks!

**Closed as completed by minggangw** 2018-09-19 08:31 UTC
